package com.ray.java.problem.chartest;

/**
 * Created by 80107442 on 2017-01-03.
 */
//注释中包含
/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0
 * Wednesday, June 17, 1998 6:44:40 o’clock AM GMT+00:00
 */
public class EscapeRout {
    public static void main(String[] args) {
// \u0022 是双引号的 Unicode 转义字符
        //1b
        System.out.println("a\u0022.length()+\u0022b".length());
    }
}
